### ISSUE TITLE
Parented entities have improper phys object calculations

### ISSUE THREAD

**Issue by Dakota0001** [DaDamRival/proper_clipping#15]
Method to produce: spawn plate, place wiremod gate on plate, spawn second plate and parent it to that gate. Clip both plates. Copy and paste. You should note that the weight of the baseplates of each are the same, however the weight of the parented plate on the copy is the weight it should be as if it were a full plate. Further investigation via physobj:GetSurfaceArea() also confirms that the duped parented plate has surface area of unclipped plate while the unparented plate clips just fine. 

I've not yet found the fix or exactly why this is caused.

**Comment by TwistedTail** [comment]
For whatever reason, the serverside physics object of the entity is one that'd be created with `ENT:PhysicsInit()` despite the clientside shows a properly cut physics object. I assume the entity hasn't finished initializing or pasting when the physical clipping begins, although this behavior is not present on unparented entities.

Here's the clientside.
![clientside](https://user-images.githubusercontent.com/8784231/96373991-5bc5ba80-1146-11eb-9566-0113c61c0a42.png)

And the serverside.
![serverside](https://user-images.githubusercontent.com/8784231/96373996-6b450380-1146-11eb-8346-dd54d5fa993f.png)

In this case the entity 151 is physically clipped and parented to 150, both show a physics object based on their model. After manually cutting 151 again, we can see the physics object is different.
![console](https://user-images.githubusercontent.com/8784231/96374014-83b51e00-1146-11eb-84d7-3a03782d17c7.png)

I did found some [weird behavior on parented entities with custom physics objects on dupe spawn in ACF some time ago](https://github.com/Stooberton/ACF-3/blob/master/lua/entities/base_scalable/init.lua#L114-L153), so I guess it's something similar.

**Comment by Dakota0001** [comment]
Further testing seems to show it is time dependent, seemingly based on if the dupe has finished spawning or not, setting the addclip function in the "duplicator.RegisterEntityModifier" function for proper clipping to have a delay of great enough time for the dupe to finish rather than it's current delay of 0 seconds results in the model being clipped on the server side. It seems to be directly related to if the entity's parent has been spawned or not in the duping process yet.
