### ISSUE TITLE
"Keep Mass" checkbox not working as expected

### ISSUE THREAD

**Issue by CheezusChrust** [DaDamRival/proper_clipping#23]
When I dupe a prop that's been clipped in physics mode, and for example 50% of the prop is clipped off, it seems to lose 50% of its mass every time it gets duped and respawned. I would assume the "Keep Mass" checkbox is supposed to prevent this but it doesn't seem to have any effect.

**Comment by Sevii77** [comment]
I'm unable to replicate this. The mass after duping and pasting is the same whether using keep mass or not.
