### ISSUE TITLE
Clips not saving in ADv Dupe 2.

### ISSUE THREAD

**Issue by Claydo9** [DaDamRival/proper_clipping#26]
When you try to save an Advanced Dupe 2 with Proper clips they do not save or possibly they don't load when you spawn said dupe back down.

**Comment by StrawWagen** [comment]
this prints in chat
Error applying entity modifer, "clips". ERROR: lua/sw_addons/modelpack/common.lua:174: bad argument #1 to 'Text' (Vector expected, got nil)

**Comment by Sevii77** [comment]
The cause is local lua and not Proper Clipping as seen from the error.
