### ISSUE TITLE
Getting errors in local server

### ISSUE THREAD

**Issue by StrawWagen** [DaDamRival/proper_clipping#27]
I'm on the x64 branch in a singleplayer local server, also get these in a normal singleplayer session.
I subscribed to the addon through the workshop.
Pasting in an advdupe2 with some physical clips and I get these errors.

[Proper Clipping] lua/autorun/server/proper_clipping.lua:183: attempt to index field 'norm' (a nil value)
    1. unknown - lua/autorun/server/proper_clipping.lua:183
    
[Proper Clipping] Warning! A net message (proper_clipping) is already started! Discarding in favor of the new message! (proper_clipping)
    1. unknown - lua/autorun/server/proper_clipping.lua:174
    
This addon is really great, never knew it was possible to cut up the hitboxes of props like this

**Comment by Sevii77** [comment]
Could you try it with a freshly clipped prop? I assume the clips might somehow be corrupted. Also avoid using another clipping addon at the same time as that might cause issues.

**Comment by StrawWagen** [comment]
Crap... It was an addon conflict causing it, I had a visual clip installed and that's what was causing the problem, you were right!
thanks!
