### ISSUE TITLE
dupes with clips are not sent to clients if they can't see them

### ISSUE THREAD

**Issue by Heatwu** [DaDamRival/proper_clipping#43]
If Client A pastes a advdupe with clip while Client B is in a visleaf that cannot see the dupe. Then Client B moves to where Client A's advdupe was pasted, Client B will be unable to load/see the ProperClip on Client A's advdupe

**Comment by vqko** [comment]
Are you sure it is not caused by another cliptool addon? It may override proper clipping' dupe logic

**Comment by Heatwu** [comment]
removing other clipping addons fixed the issue, closing
